services:
  zerium:
    build: .
    container_name: zerium
    
  zerium_nginx:
    image: nginx:alpine
    container_name: zerium_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
    depends_on:
      - zerium

networks:
  default:
    name: proxy-manager
    external: true
