import type { Metadata } from "next";
import "./globals.css";
import { Roboto, Poppins } from 'next/font/google';
import path from "path";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal' , 'italic'],
  variable: '--font-main',
  subsets: ['latin'],
});

const poppins = Poppins({
  weight: ["400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-secondary",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${roboto.variable} ${poppins.variable}`}>
      <body className="relative">{children}</body>
    </html>
  );
}
