import type { Metadata } from "next";
import "./globals.css";
import { Roboto } from 'next/font/google';
import path from "path";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ['400', '500', '700'],
  style: ['normal' , 'italic'],
  variable: '--font-main',
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={`${roboto.variable}`}>
      <body className="relative">{children}</body>
    </html>
  );
}
